vim.syntax_on = true
vim.wo.number = true
vim.wo.relativenumber = true
vim.bo.tabstop = __.codestyle.tab_size
vim.bo.softtabstop = __.codestyle.tab_size
vim.bo.shiftwidth = __.codestyle.tab_size
vim.cmd("set sw=" .. __.codestyle.tab_size)
vim.cmd("set ts=" .. __.codestyle.tab_size)
vim.o.smarttab = true
vim.bo.expandtab = __.codestyle.expandtab
vim.bo.autoindent = true
vim.bo.smartindent = true
vim.bo.copyindent = true
vim.o.clipboard = "unnamedplus"
vim.o.autoread = true
vim.o.backup = false
vim.o.writebackup = false
vim.wo.cursorline = true
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.mouse = "a"
vim.o.timeoutlen = 750
vim.wo.wrap = false
vim.o.completeopt = "menuone,noselect"
vim.o.undofile = true
vim.cmd("set undodir=$HOME/.config/nvim/undodir")
vim.o.termguicolors = true
vim.o.hidden = true
vim.cmd("language " .. __.language)
