require("config.plugins.compe")
require("config.plugins.null-ls")
require("config.plugins.dashboard")
require("config.plugins.galaxyline")
require("config.plugins.gitsigns")
require("config.plugins.lsp")
require("config.plugins.lspkind")
require("config.plugins.nvcode")
require("config.plugins.nvim-toggleterm")
require("config.plugins.nvim-tree")
require("config.plugins.telescope")
require("config.plugins.treesitter")
require("config.plugins.vim-rooter")
require("config.plugins.vsnip")
require("config.plugins.which-key")
require("config.plugins.symbols-outline")
require("config.plugins.diffview")
-- require("config.plugins.dap")

-- Just loaders, without settings

require("colorizer").setup()
require("lspsaga").init_lsp_saga()
require("todo-comments").setup()
require('nvim_comment').setup()
require("trouble").setup()
