-- require("config.plugins.compe")
require("config.plugins.cmp")
require("config.plugins.null-ls")
require("config.plugins.dashboard")
require("config.plugins.galaxyline")
require("config.plugins.gitsigns")
require("config.plugins.lsp")
require("config.plugins.lspkind")
require("config.plugins.nvim-toggleterm")
require("config.plugins.nvim-tree")
require("config.plugins.telescope")
require("config.plugins.treesitter")
-- require("config.plugins.which-key")
require("config.plugins.symbols-outline")
require("config.plugins.diffview")
require("config.plugins.indent-blankline")
require("config.plugins.nvim-comment")
-- require("config.plugins.dap")

-- Just loaders, without settings

require("lsp-rooter").setup({})
require("colorizer").setup()
require("lspsaga").init_lsp_saga()
require("todo-comments").setup()
require("trouble").setup()
require("nvim-autopairs").setup()
